name: ci

name: ManuallyTriggerDockerBuilding
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag version'
        required: true
        default: 'dev'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GPU version
        uses: docker/build-push-action@v2
        with:
          context: ./final_project
          build-args: |
            BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
          file: ./final_project/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: khjtony/bme4030-project-gpu:${{ github.event.inputs.tag }}
      -
        name: Build and push CPU version
        uses: docker/build-push-action@v2
        with:
          context: ./final_project
          build-args: |
            BASE_IMAGE=ubuntu:18.04
          file: ./final_project/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: khjtony/bme4030-project-cpu:${{ github.event.inputs.tag }}